version: "3.3"
services:
  api:
    build:
      context: api
      dockerfile: docker/Dockerfile
  app:
    depends_on: [api]
    build:
      context: app
      dockerfile: docker/prod.Dockerfile
    ports:
      - "80:80"
