version: 2.1
jobs:
  test_app:
    working_directory: ~/chess-recognition-app/app
    docker:
      - image: circleci/node:15
    steps:
      - checkout:
          path: ~/chess-recognition-app
      - restore_cache:
          key: npm-cache-v1-{{ checksum "package-lock.json" }}
      - run:
          name: Install Dependencies
          command: npm ci
      - save_cache:
          key: npm-cache-v1-{{ checksum "package-lock.json" }}
          paths:
            - /home/circleci/.npm
      - run:
          name: Run Tests
          command: npm run test:ci
          environment:
            JEST_JUNIT_OUTPUT_DIR: ./reports/junit/
      - store_test_results:
          path: ./reports/junit/
      - store_artifacts:
          path: ./reports/junit
  test_api:
    working_directory: ~/chess-recognition-app/api
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout:
          path: ~/chess-recognition-app
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.8/site-packages
      - restore_cache:
          key: deps9-{{ .Branch }}-{{ checksum "poetry.lock" }}
      - run:
          command: |
            sudo pip install poetry
            poetry install
      - save_cache:
          key: deps9-{{ .Branch }}-{{ checksum "poetry.lock" }}
          paths:
            - "~/.cache/pypoetry/virtualenvs"
      - run:
          command: |
            mkdir test-results
            poetry run python -m pytest --junitxml=test-results/junit.xml
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
          destination: tr1
workflows:
  version: 2
  workflow:
    jobs:
      - test_app
      - test_api
