[tool.poetry]
name = "chess-recognition-api"
version = "0.1.0"
description = "Chess recognition backend API"
authors = ["Georg Wölflein <georgw7777@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
fastapi = "^0.61.2"
python-chess = "^1.999"
python-multipart = "^0.0.5"
opencv-python = "^4.4.0"
numpy = "^1.19.4"
chess-recognition = {git = "https://github.com/georgw777/chess-recognition.git", rev = "v0.1.1"}

[tool.poetry.dev-dependencies]
autopep8 = "^1.5.4"
pylint = "^2.6.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
