name: Node.js build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache
        uses: actions/cache@v2.1.3
        with:
          path: app/node_modules
          key: node_modules-${{ runner.os }}-${{ matrix.node-version }}-${{ hashFiles('app/**/package-lock.json') }}
      - name: Install dependencies
        run: npm ci
        working-directory: app
      - name: Build
        run: npm run build
        working-directory: app
      - name: Test
        run: npm test
        working-directory: app
