name: upgrade chesscog

on:
  repository_dispatch:
    types: [chesscog_release]

jobs:
  upgrade_chesscog:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install Poetry
        uses: snok/install-poetry@v1.1.1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
      - name: Install dependencies
        run: poetry install
        working-directory: api
      - name: Install new chesscog version
        run: poetry add git+https://github.com/georgw777/chesscog.git#${{ github.event.client_payload.chesscog_version }}
        working-directory: api
      - name: Create pull request
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: Bump chesscog version to ${{ github.event.client_payload.chesscog_version }}
          title: Bump chesscog version to ${{ github.event.client_payload.chesscog_version }}
          body: Automatically generated pull request by CI due to a new version of chesscog being released.
          delete-branch: true
          branch: bump_chesscog_version/${{ github.event.client_payload.chesscog_version }}
